!!python/object/apply:collections.OrderedDict
- - - delta_std
    - 0.025
  - - env_wrapper
    - - quadruped_spring.env.wrappers.landing_wrapper.LandingWrapper
      - quadruped_spring.env.wrappers.obs_flattening_wrapper.ObsFlatteningWrapper
  - - learning_rate
    - 0.03
  - - n_delta
    - 40
  - - n_envs
    - 20
  - - n_timesteps
    - 75000000.0
  - - n_top
    - 30
  - - normalize
    - dict(norm_obs=True, norm_reward=False)
  - - policy
    - MlpPolicy
  - - policy_kwargs
    - dict(net_arch=[16],activation_fn=nn.Tanh)
